### PR TITLE
[WIP] Add edition numbers for all bibliographic items

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
As per https://github.com/relaton/relaton-data-iho/issues/20

### CODE REVIEW

**Comment by manuelfuenmayor** [comment]
@ronaldtse, in all YAMLs there is this markup:

```yaml
...
editorialgroup:
- - committee:
      abbreviation: HSSC
      name: Hydrographic Services and Standards Committee
...
````

This part: `- - committee:`, seems to be wrong. Could you confirm?

**Comment by ronaldtse** [comment]
> This part: `- - committee:`, seems to be wrong.

I think this is wrong but let's have @andrew2net confirm. Thanks.

**Comment by manuelfuenmayor** [comment]
@ronaldtse, in the case of B-7, I found a website that says that the publication is under revision:
iho_b-7

Source: https://www.gebco.net/about_us/guidelines/

Maybe this is the reason I can't find the edition number for this publication?

**Comment by ronaldtse** [comment]
B7 was previously punished. Can you please find the old one and the edition number?

**Comment by andrew2net** [comment]
> This part: `- - committee:`, seems to be wrong.

@manuelfuenmayor yes, it's wrong. It definetely should be like you suggest.

**Comment by andrew2net** [comment]
> This part: `- - committee:`, seems to be wrong.

@manuelfuenmayor I'm sorry. It's not wrong. It's correct for IHO. My bad.

**Comment by manuelfuenmayor** [comment]
@ronaldtse, for S-53, the edition number is indicated as a date format:
iho-s53-1

What should we do in this case?
Maybe put the date as the edition? :

```yaml
edition:
  content: 01-2016
````

**Comment by ronaldtse** [comment]
> What should we do in this case? Maybe put the date as the edition? :

Please file a new issue for this so we can ask IHO. The edition MUST BE x.y.z.

> However, I've looked at other publications that do have explicit edition numbers and this "version number" is not always equal to them.

Please file a new issue for these, thanks.

**Comment by manuelfuenmayor** [comment]
> Please file a new issue for these, thanks.

Done

**Pull request merged**
